features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
favicon:
  use_default: true
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_translation: 0
header_extended: 1
mega_menu: 1
footer_extended: 1
footer_extended_message: 'California Courts San Diego'
color_inverted: 0
