third_party_settings:
  field_group:
    group_main_content:
      label: 'Acerca de'
    group_address:
      label: Dirección
    group_hours:
      label: Horas
    group_phone:
      label: Teléfono
