display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
            first: '« Primero'
            last: 'Último »'
      fields:
        title:
          separator: ', '
        body:
          separator: ', '
        field_department:
          separator: ', '
        field_division:
          separator: ', '
        field_subject_matter:
          separator: ', '
        field_tags:
          separator: ', '
        field_topics:
          separator: ', '
      filters:
        field_tags_target_id:
          expose:
            label: Etiquetas
        field_topics_target_id:
          expose:
            label: Temas
  block_1:
    display_options:
      fields:
        title:
          separator: ', '
        body:
          separator: ', '
        field_department:
          separator: ', '
        field_division:
          separator: ', '
        field_subject_matter:
          separator: ', '
        field_tags:
          separator: ', '
        field_topics:
          separator: ', '
      arguments:
        tid:
          exception:
            title: Todo(s)
        tid_1:
          exception:
            title: Todo(s)
