features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://logo_0.png'
favicon:
  use_default: true
facebook: 'https://www.facebook.com/CaliforniaCourts/'
twitter: 'https://twitter.com/CalCourts'
youtube: 'https://www.youtube.com/californiacourts'
email: ''
flickr: ''
linkedin: ''
rss: ''
hide_translation: 0
header_extended: 1
mega_menu: 1
footer_extended: 0
footer_extended_message: ''
color_inverted: 0
