session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    zh-hans: zh-hans
    zh-hant: zh-hant
    vi: vi
    fil: fil
    pa: pa
    ko: ko
    fa: fa
    ar: ar
    mam: mam
    tir: tir
  domains:
    en: ''
    es: ''
    zh-hans: ''
    zh-hant: ''
    vi: ''
    fil: ''
    pa: ''
    ko: ''
    fa: ''
    ar: ''
    mam: ''
    tir: ''
selected_langcode: site_default
_core:
  default_config_hash: X8jLEfKCIINnbLrRvcDQaiRgyNVR3Jv0xW5RVYDutYE
