session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    ko: ko
    zh-hant: zh-hant
    ru: ru
    vi: vi
  domains:
    en: ''
    es: ''
    vi: ''
selected_langcode: site_default
_core:
  default_config_hash: X8jLEfKCIINnbLrRvcDQaiRgyNVR3Jv0xW5RVYDutYE
