iconset: social-icons--square
_core:
  default_config_hash: xG-M6wrdMJhjfod4XLo5uXFM6-AerFMiXrfX_ykr4NY
services:
  facebook: facebook
  twitter: twitter
  email: email
  linkedin: linkedin
  whatsapp: 0
  facebook_messenger: 0
  pinterest: 0
  googleplus: 0
  digg: 0
  stumbleupon: 0
  delicious: 0
  slashdot: 0
  tumblr: 0
  reddit: 0
  evernote: 0
  copy: 0
width: 30px
height: 30px
radius: 3px
facebook_app_id: ''
