ignored_config_entities:
  - jcc_base.settings
  - openid_connect.settings.windows_aad
  - geocoder.geocoder_provider.bingmaps
  - system.site
  - extlink.settings
  - block.block.jccglossifypathexclusion
  - block.block.jccbooknavigationblock
  - social_post_twitter.settings
_core:
  default_config_hash: w1F6gmM_hfR7_7r1dXLiPCxGdjQWOxM4ABrefOp08-E
