blacklisted_source_paths:
  - /admin
  - /block
  - /comment
  - /media
  - /node
  - /system
  - /taxonomy
  - /user
  - /views
_core:
  default_config_hash: UNSGvKfOwAhcC1woOmvMwe9m8TLBkK_QuuGJZt_iEU8
