name: 'SITE NAME'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: 0SUApmezO8-NNdrDkgUc9ueNqLHOVVeojzsZpH_T-L8
uuid: 751a0f52-dcd3-4141-86d9-f568af0e3a02
