display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
          text_input_required: 'Seleccione cualquier filtro y pulse Aplicar para ver los resultados'
          bef:
            general:
              secondary_label: 'Opciones avanzadas'
      fields:
        title:
          separator: ', '
        field_attachments:
          separator: ', '
        field_division:
          separator: ', '
        field_document_type:
          separator: ', '
        field_subject_matter:
          separator: ', '
        field_topics:
          separator: ', '
        field_upload_date:
          separator: ', '
      filters:
        title:
          expose:
            label: Título
  page_1:
    display_title: Página
