# Schema for the configuration files of the jcc_migrate_source_ui module.

jcc_migrate_source_ui.settings:
  type: config_object
  label: 'JCC Migrate Source logging settings'
  mapping:
    row_limit:
      type: integer
      label: 'JCC Migrate Source log messages to keep'
