# Schema for the views plugins of the Database Logging module.

views.field.jcc_migrate_source_log_message:
  type: views_field
  label: 'Log event message'
  mapping:
    replace_variables:
      type: boolean
      label: 'Replace variables'
