third_party_settings:
  field_group:
    group_content:
      label: Contenido
    group_metadata:
      label: 'Meta datos'
    group_settings:
      label: Configuración
content:
  field_paragraphs:
    settings:
      title: Párrafo
      title_plural: Parráfos
