name: Resumen
facets:
  content:
    label: Contenido
    separator: ', '
  department:
    label: Departamento
    separator: ', '
  division:
    separator: ', '
  document_type:
    separator: ', '
  event_type:
    separator: ', '
  location_type:
    separator: ', '
  news_type:
    separator: ', '
  person_type:
    separator: ', '
  subject_matter:
    separator: ', '
  tags:
    label: Etiquetas
    separator: ', '
  topics:
    label: Temas
    separator: ', '
processor_configs:
  show_text_when_empty:
    settings:
      text:
        value: 'No se han encontrado resultados.'
