text:
  -
    value: "<p>A new article has been posted!</p>\r\n\r\n<p><a href=\"[message:field_node_ref:entity:url]\">[message:field_node_ref:entity:title]</a></p>\r\n\r\n<p>[message:field_node_ref:entity:body]</p>\r\n"
    format: full_html
