tips:
  announcement-title:
    label: Título
  announcement-body:
    label: Cuerpo
  announcement-visibility-global:
    label: Visibilidad
  announcement-scheduler-publish:
    label: Publicar
  announcement-scheduler-unpublish:
    label: Despublicar
