name: Resumen
facets:
  content:
    label: Contenido
    separator: ', '
  department:
    separator: ', '
  division:
    separator: ', '
  document_type:
    separator: ', '
  event_type:
    separator: ', '
  location_type:
    separator: ', '
  news_type:
    separator: ', '
  person_type:
    separator: ', '
  subject_matter:
    separator: ', '
  tags:
    label: Etiquetas
    separator: ', '
  topics:
    label: Temas
    separator: ', '
