facets:
  content:
    label: Content
    separator: ', '
  department:
    separator: ', '
  division:
    separator: ', '
  document_type:
    separator: ', '
  event_type:
    separator: ', '
  location_type:
    separator: ', '
  news_type:
    separator: ', '
  person_type:
    separator: ', '
  subject_matter:
    separator: ', '
  tags:
    separator: ', '
  topics:
    separator: ', '
