display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            first: '« First'
            last: 'Last »'
      fields:
        thumbnail__target_id:
          separator: ', '
        name:
          separator: ', '
        bundle:
          separator: ', '
        uid:
          separator: ', '
        status:
          settings:
            format_custom_true: Published
            format_custom_false: Unpublished
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: Operations
      filters:
        status:
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
