display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        title:
          separator: ', '
        field_display_on_all_pages:
          separator: ', '
      arguments:
        field_specific_visibility_target_id:
          exception:
            title: All
  block_1:
    display_options:
      arguments:
        field_specific_visibility_target_id:
          exception:
            title: All
  page_1:
    display_title: Page
    display_options:
      fields:
        title:
          separator: ', '
