display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        title:
          label: Title
          separator: ', '
        type:
          separator: ', '
        name:
          separator: ', '
        status:
          settings:
            format_custom_true: Published
            format_custom_false: Unpublished
          separator: ', '
        publish_on:
          separator: ', '
        unpublish_on:
          separator: ', '
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: 'Content type'
        status:
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
    display_title: Master
  overview:
    display_options:
      tab_options:
        title: Content
  user_page:
    display_options:
      tab_options:
        title: Content
      arguments:
        uid:
          exception:
            title: All
