display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        subject:
          separator: ', '
        uid:
          separator: ', '
        name:
          separator: ', '
        entity_id:
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: Operations
        name_1:
          separator: ', '
  page_unapproved:
    display_options:
      fields:
        subject:
          separator: ', '
        uid:
          separator: ', '
        name:
          separator: ', '
        entity_id:
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: Operations
        name_1:
          separator: ', '
