display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        title:
          separator: ', '
        field_attachments:
          separator: ', '
        field_division:
          separator: ', '
        field_document_type:
          separator: ', '
        field_subject_matter:
          separator: ', '
        field_topics:
          separator: ', '
        field_upload_date:
          separator: ', '
      filters:
        title:
          expose:
            label: Title
  page_1:
    display_title: Page
