label: Content
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            first: '« First'
            last: 'Last »'
      fields:
        title:
          label: Title
        type:
          label: 'Content type'
          separator: ', '
        status:
          settings:
            format_custom_true: Published
            format_custom_false: Unpublished
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: 'Content type'
        status:
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
      title: Content
    display_title: Master
  page_1:
    display_options:
      menu:
        title: Content
      tab_options:
        title: Content
    display_title: Page
