display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      filters:
        status:
          group_info:
            label: Published
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
  page:
    display_title: Page
    display_options:
      fields:
        name:
          separator: ', '
  widget:
    display_options:
      arguments:
        bundle:
          exception:
            title: All
  widget_table:
    display_options:
      arguments:
        bundle:
          exception:
            title: All
