name: 'SITE NAME'
mail: jcc@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: 0SUApmezO8-NNdrDkgUc9ueNqLHOVVeojzsZpH_T-L8
uuid: 80b602b2-bd28-4bbf-aea1-cdb20f338034
