name: 'SITE NAME'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/27
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: 39xtgXrOgWf5RNUvb1GEpd2NaWLBt_9KL4Ue2DG3NJk
uuid: 7912a872-7683-41d0-8bd4-6b1458dd8fb7
