display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
      fields:
        sid:
          label: Nº
        in_draft:
          label: Borrador
        view_webform_submission:
          label: Operations
  embed_administer:
    display_options:
      fields:
        sid:
          label: Nº
        in_draft:
          label: Borrador
        operations:
          label: Operations
  embed_manage:
    display_options:
      fields:
        sid:
          label: Nº
        in_draft:
          label: Borrador
        view_webform_submission:
          label: Operations
        edit_webform_submission:
          label: Operations
  embed_review:
    display_options:
      fields:
        sid:
          label: Nº
        in_draft:
          label: Borrador
        view_webform_submission:
          label: Operations
