display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹
            next: ›
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        title:
          separator: ', '
        field_display_on_all_pages:
          separator: ', '
      arguments:
        field_specific_visibility_target_id:
          exception:
            title: Todo(s)
      use_more_text: más
  block_1:
    display_options:
      arguments:
        field_specific_visibility_target_id:
          exception:
            title: Todo(s)
  page_1:
    display_title: Página
    display_options:
      fields:
        title:
          separator: ', '
