bundle: jcc_tc2
excluded:
  - encrypt.profile.tfa
  - language.content_settings.contact_message.feedback
  - language.content_settings.contact_message.personal
  - language.entity.en
  - language.entity.es
  - language.entity.und
  - language.entity.zxx
  - language.mappings
  - language.negotiation
  - system.action.user_add_role_action.contributor
  - system.action.user_remove_role_action.contributor
  - system.action.user_add_role_action.author
  - system.action.user_remove_role_action.author
  - user.role.contributor
  - user.role.author
required: true
