bundle: jcc_tc2
excluded:
  - language.content_settings.contact_message.feedback
  - language.content_settings.contact_message.personal
  - encrypt.profile.tfa
  - language.mappings
  - language.negotiation
  - language.entity.en
  - language.entity.es
  - language.entity.und
  - language.entity.zxx
required: true
